{% set version = "22.6.0" %}
{% set hash = "b266c95d2d955941aec61901fc5959850a8ec1ac9c2cdf5253b5b6d3f44efe12" %}
{% set build_number = "0" %}

package:
  name: conda-libmamba-solver
  version: {{ version }}

source:
  url: https://github.com/conda-incubator/conda-libmamba-solver/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
    - flit-core >=3.2,<4
  run:
    - python >=3.6
    - libmambapy >=0.23
    - conda >=4.12
    - importlib_metadata

test:
  imports:
    - conda_libmamba_solver
  commands:
    - CONDA_SOLVER_LOGIC=libmamba conda create -n test --dry-run scipy

about:
  home: https://github.com/conda-incubator/conda-libmamba-solver
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'The fast mamba solver, now in conda!'
  dev_url: https://github.com/conda-incubator/conda-libmamba-solver
  doc_url: https://github.com/conda-incubator/conda-libmamba-solver/README.md
