{% set version = "23.3.0" %}

package:
  name: conda-libmamba-solver
  version: {{ version }}

source:
  url: https://github.com/conda/conda-libmamba-solver/archive/refs/tags/{{ version }}.tar.gz
  sha256: 0c209980d10d2acf3bb070f2a00c157319efc49f313e23992f7c350a37d98a87
  folder: src/

build:
  skip: true  # [py<38]
  # trigger 1
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{version}}
  script: {{ PYTHON }} -m pip install src/ -vv --no-deps

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
    - hatchling
    - hatch-vcs
  run:
    - python
    - conda >=23.3.1
    - libmambapy >=1.4.1
    - boltons >=23.0.0

test:
  imports:
    - conda_libmamba_solver
  commands:
    - CONDA_SOLVER=libmamba conda create -n test --dry-run scipy  # [not win]  Not crosss platform.
    - conda create --solver libmamba -n test --dry-run scipy

about:
  home: https://github.com/conda/conda-libmamba-solver
  license: BSD-3-Clause
  license_family: BSD
  license_file: src/LICENSE
  summary: 'The fast mamba solver, now in conda!'
  description: |
    The conda-libmamba-solver is a new solver for the conda package manager
    which uses the solver from the mamba project behind the scenes,
    while carefully implementing conda's functionality and expected behaviors on top.
    The library used by mamba to do the heavy-lifting is called libsolv.
  dev_url: https://github.com/conda/conda-libmamba-solver
  doc_url: https://conda.github.io/conda-libmamba-solver/

extra:
  recipe-maintainers:
    - jaimergp
    - jezdez
    - wolfv
  skip-lints:
    - missing_pip_check
