{% set name = "conda-libmamba-solver" %}
{% set version = "23.9.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/conda/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: f156e931e47091ecf568a54a50edf1eecf6dbf07154cb0dca163bd0af38d4a13
  folder: src/

build:
  number: 0
  skip: true  # [py<38]
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{version}}
  script: {{ PYTHON }} -m pip install src/ -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python
    - conda >=23.7.4
    - libmambapy >=1.5.1
    - boltons >=23.0.0

test:
  imports:
    - conda_libmamba_solver
  commands:
    - CONDA_SOLVER=libmamba conda create -n test --dry-run scipy  # [not win]  Not crosss platform.
    - conda create --solver libmamba -n test --dry-run scipy

about:
  home: https://github.com/conda/conda-libmamba-solver
  license: BSD-3-Clause
  license_family: BSD
  license_file: src/LICENSE
  summary: 'The fast mamba solver, now in conda!'
  description: |
    The conda-libmamba-solver is a new solver for the conda package manager
    which uses the solver from the mamba project behind the scenes,
    while carefully implementing conda's functionality and expected behaviors on top.
    The library used by mamba to do the heavy-lifting is called libsolv.
  dev_url: https://github.com/conda/conda-libmamba-solver
  doc_url: https://conda.github.io/conda-libmamba-solver/

extra:
  recipe-maintainers:
    - jaimergp
    - jezdez
    - wolfv
  skip-lints:
    - missing_pip_check
