{% set version = "23.1.0" %}
{% set hash = "090070a54572236f8e23263659520a27c31161e595a1c4feaffb70263d86a32e" %}
{% set build_number = "0" %}

package:
  name: conda-libmamba-solver
  version: {{ version }}

source:
  url: https://github.com/conda/conda-libmamba-solver/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  skip: true  # [py<37]
  number: {{ build_number }}
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
    - flit-core >=3.2,<4
  run:
    - python
    - libmambapy >=1.0.0
    - conda >=22.11.0
    - importlib-metadata

test:
  imports:
    - conda_libmamba_solver
  commands:
    - CONDA_SOLVER=libmamba conda create -n test --dry-run scipy  # [not win]  Not crosss platform.
    - conda create --solver libmamba -n test --dry-run scipy

about:
  home: https://github.com/conda/conda-libmamba-solver
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'The fast mamba solver, now in conda!'
  description: |
    The conda-libmamba-solver is a new solver for the conda package manager 
    which uses the solver from the mamba project behind the scenes, 
    while carefully implementing conda's functionality and expected behaviors on top. 
    The library used by mamba to do the heavy-lifting is called libsolv.
  dev_url: https://github.com/conda/conda-libmamba-solver
  doc_url: https://conda.github.io/conda-libmamba-solver/

extra:
  recipe-maintainers:
    - jaimergp
    - jezdez
    - wolfv
  skip-lints:
    - missing_pip_check