{% set name = "conda-libmamba-solver" %}
{% set version = "25.3.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/conda/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 1e143b573aff06ee2b96961eaaff389b50e060c15342b44a0ae1def77760ba15
  folder: src/

build:
  number: 0
  # build as noarch to avoid circular dependency issues in conda when
  # adding support for new Python versions
  noarch: python
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{version}}
  script: {{ PYTHON }} -m pip install src/ -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.9
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >=3.9
    - conda >=23.7.4
    - libmambapy >=2
    - boltons >=23.0.0

test:
  imports:
    - conda_libmamba_solver
  commands:
    - CONDA_SOLVER=libmamba conda create -n test --dry-run scipy  # [not win]  Not crosss platform.
    - conda create --solver libmamba -n test --dry-run scipy

about:
  home: https://github.com/conda/conda-libmamba-solver
  license: BSD-3-Clause
  license_family: BSD
  license_file: src/LICENSE
  summary: 'The fast mamba solver, now in conda!'
  description: |
    The conda-libmamba-solver is a new solver for the conda package manager
    which uses the solver from the mamba project behind the scenes,
    while carefully implementing conda's functionality and expected behaviors on top.
    The library used by mamba to do the heavy-lifting is called libsolv.
  dev_url: https://github.com/conda/conda-libmamba-solver
  doc_url: https://conda.github.io/conda-libmamba-solver/

extra:
  recipe-maintainers:
    - jaimergp
    - jezdez
    - wolfv
  skip-lints:
    - missing_pip_check
